# Database configuration for Rails

# Default settings for all environments
# Local development uses Docker Compose's `db` service
# Production expects DATABASE_URL to be provided by the platform

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>

# Development environment
# Using postgres service provided by docker-compose
development:
  <<: *default
  database: myapp_development

# Test environment
# Same settings as development but separate database name
# Database will be created automatically when running tests

test:
  <<: *default
  database: myapp_test

# Production environment
# Render provides DATABASE_URL which contains the full connection string
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
